
UPDATE DEPT SET LOC = 'BOSTON' WHERE DEPTNO = 10;

UPDATE EMP SET SAL = SAL + 500 WHERE JOB = 'SALESMAN';

UPDATE BONUS SET COMM = 100 WHERE ENAME = 'SMITH';

UPDATE SALGRADE SET LOSAL = 750 WHERE GRADE = 1;
